//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace digital_Library.modals
{
    using System;
    using System.Collections.Generic;
    
    public partial class images_Paid
    {
        public int id { get; set; }
        public string R_image { get; set; }
        public Nullable<int> id_student { get; set; }
        public Nullable<bool> paid { get; set; }
        public Nullable<bool> employee_reply { get; set; }
    }
}
