//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace digital_Library.modals
{
    using System;
    using System.Collections.Generic;
    
    public partial class merchent_ref_number
    {
        public int id { get; set; }
        public string merchent_ref_num { get; set; }
    }
}
