//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace digital_Library.modals
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        public int id_student { get; set; }
        public string name_student { get; set; }
        public string national_id { get; set; }
        public string password_student { get; set; }
        public Nullable<int> faculty_id { get; set; }
        public string phone { get; set; }
        public string Job { get; set; }
        public string Job_place { get; set; }
        public string email_address { get; set; }
        public string department { get; set; }
        public string Division { get; set; }
        public string Specialization { get; set; }
        public string academic_year { get; set; }
        public string chart_title { get; set; }
        public string Supervisor { get; set; }
        public string Co_supervisor { get; set; }
        public string notes { get; set; }
        public Nullable<bool> Flag_pay { get; set; }
        public string date_pay { get; set; }
        public string date_print { get; set; }
        public Nullable<int> iduniversity { get; set; }
        public string degree_academic { get; set; }
        public string search_date { get; set; }
        public string employee_user { get; set; }
        public string refnumber { get; set; }
        public string arabic_address { get; set; }
        public string eng_add { get; set; }
        public string univ_name { get; set; }
        public Nullable<byte> status { get; set; }
        public string student_file { get; set; }
        public string refNumber_fawry { get; set; }
        public string signture { get; set; }
    }
}
